services:
    bota:
        build:
          context: .
          dockerfile: ./Dockerfile
        image: algielen/botamusique
        container_name: bota
        hostname: bota
        #network_mode: bridge
        restart: no
        #env_file: .env
        environment:
            BAM_CONFIG_FILE: /config/config.ini
            BAM_MUSIC_DB: /music/music.db
            BAM_DB: /config/settings-bota.db
            BAM_VERBOSE: true
        volumes:
            - ./tmp/music:/music
            - ./tmp/config:/config

# after changes: docker compose up --build bota
# sudo chown -R 568:568 tmp/